// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ClusterValidationID cluster validation id
//
// swagger:model cluster-validation-id
type ClusterValidationID string

func NewClusterValidationID(value ClusterValidationID) *ClusterValidationID {
	v := value
	return &v
}

const (

	// ClusterValidationIDMachineDashCidrDashDefined captures enum value "machine-cidr-defined"
	ClusterValidationIDMachineDashCidrDashDefined ClusterValidationID = "machine-cidr-defined"

	// ClusterValidationIDClusterDashCidrDashDefined captures enum value "cluster-cidr-defined"
	ClusterValidationIDClusterDashCidrDashDefined ClusterValidationID = "cluster-cidr-defined"

	// ClusterValidationIDServiceDashCidrDashDefined captures enum value "service-cidr-defined"
	ClusterValidationIDServiceDashCidrDashDefined ClusterValidationID = "service-cidr-defined"

	// ClusterValidationIDNoDashCidrsDashOverlapping captures enum value "no-cidrs-overlapping"
	ClusterValidationIDNoDashCidrsDashOverlapping ClusterValidationID = "no-cidrs-overlapping"

	// ClusterValidationIDNetworkDashPrefixDashValid captures enum value "network-prefix-valid"
	ClusterValidationIDNetworkDashPrefixDashValid ClusterValidationID = "network-prefix-valid"

	// ClusterValidationIDMachineDashCidrDashEqualsDashToDashCalculatedDashCidr captures enum value "machine-cidr-equals-to-calculated-cidr"
	ClusterValidationIDMachineDashCidrDashEqualsDashToDashCalculatedDashCidr ClusterValidationID = "machine-cidr-equals-to-calculated-cidr"

	// ClusterValidationIDAPIDashVipDashDefined captures enum value "api-vip-defined"
	ClusterValidationIDAPIDashVipDashDefined ClusterValidationID = "api-vip-defined"

	// ClusterValidationIDAPIDashVipDashValid captures enum value "api-vip-valid"
	ClusterValidationIDAPIDashVipDashValid ClusterValidationID = "api-vip-valid"

	// ClusterValidationIDIngressDashVipDashDefined captures enum value "ingress-vip-defined"
	ClusterValidationIDIngressDashVipDashDefined ClusterValidationID = "ingress-vip-defined"

	// ClusterValidationIDIngressDashVipDashValid captures enum value "ingress-vip-valid"
	ClusterValidationIDIngressDashVipDashValid ClusterValidationID = "ingress-vip-valid"

	// ClusterValidationIDAllDashHostsDashAreDashReadyDashToDashInstall captures enum value "all-hosts-are-ready-to-install"
	ClusterValidationIDAllDashHostsDashAreDashReadyDashToDashInstall ClusterValidationID = "all-hosts-are-ready-to-install"

	// ClusterValidationIDSufficientDashMastersDashCount captures enum value "sufficient-masters-count"
	ClusterValidationIDSufficientDashMastersDashCount ClusterValidationID = "sufficient-masters-count"

	// ClusterValidationIDDNSDashDomainDashDefined captures enum value "dns-domain-defined"
	ClusterValidationIDDNSDashDomainDashDefined ClusterValidationID = "dns-domain-defined"

	// ClusterValidationIDPullDashSecretDashSet captures enum value "pull-secret-set"
	ClusterValidationIDPullDashSecretDashSet ClusterValidationID = "pull-secret-set"

	// ClusterValidationIDNtpDashServerDashConfigured captures enum value "ntp-server-configured"
	ClusterValidationIDNtpDashServerDashConfigured ClusterValidationID = "ntp-server-configured"

	// ClusterValidationIDLsoDashRequirementsDashSatisfied captures enum value "lso-requirements-satisfied"
	ClusterValidationIDLsoDashRequirementsDashSatisfied ClusterValidationID = "lso-requirements-satisfied"

	// ClusterValidationIDOcsDashRequirementsDashSatisfied captures enum value "ocs-requirements-satisfied"
	ClusterValidationIDOcsDashRequirementsDashSatisfied ClusterValidationID = "ocs-requirements-satisfied"

	// ClusterValidationIDCnvDashRequirementsDashSatisfied captures enum value "cnv-requirements-satisfied"
	ClusterValidationIDCnvDashRequirementsDashSatisfied ClusterValidationID = "cnv-requirements-satisfied"

	// ClusterValidationIDNetworkDashTypeDashValid captures enum value "network-type-valid"
	ClusterValidationIDNetworkDashTypeDashValid ClusterValidationID = "network-type-valid"
)

// for schema
var clusterValidationIdEnum []interface{}

func init() {
	var res []ClusterValidationID
	if err := json.Unmarshal([]byte(`["machine-cidr-defined","cluster-cidr-defined","service-cidr-defined","no-cidrs-overlapping","network-prefix-valid","machine-cidr-equals-to-calculated-cidr","api-vip-defined","api-vip-valid","ingress-vip-defined","ingress-vip-valid","all-hosts-are-ready-to-install","sufficient-masters-count","dns-domain-defined","pull-secret-set","ntp-server-configured","lso-requirements-satisfied","ocs-requirements-satisfied","cnv-requirements-satisfied","network-type-valid"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		clusterValidationIdEnum = append(clusterValidationIdEnum, v)
	}
}

func (m ClusterValidationID) validateClusterValidationIDEnum(path, location string, value ClusterValidationID) error {
	if err := validate.EnumCase(path, location, value, clusterValidationIdEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this cluster validation id
func (m ClusterValidationID) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateClusterValidationIDEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this cluster validation id based on context it is used
func (m ClusterValidationID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
