// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// HostValidationID host validation id
//
// swagger:model host-validation-id
type HostValidationID string

func NewHostValidationID(value HostValidationID) *HostValidationID {
	v := value
	return &v
}

const (

	// HostValidationIDConnected captures enum value "connected"
	HostValidationIDConnected HostValidationID = "connected"

	// HostValidationIDHasDashInventory captures enum value "has-inventory"
	HostValidationIDHasDashInventory HostValidationID = "has-inventory"

	// HostValidationIDHasDashMinDashCPUDashCores captures enum value "has-min-cpu-cores"
	HostValidationIDHasDashMinDashCPUDashCores HostValidationID = "has-min-cpu-cores"

	// HostValidationIDHasDashMinDashValidDashDisks captures enum value "has-min-valid-disks"
	HostValidationIDHasDashMinDashValidDashDisks HostValidationID = "has-min-valid-disks"

	// HostValidationIDHasDashMinDashMemory captures enum value "has-min-memory"
	HostValidationIDHasDashMinDashMemory HostValidationID = "has-min-memory"

	// HostValidationIDMachineDashCidrDashDefined captures enum value "machine-cidr-defined"
	HostValidationIDMachineDashCidrDashDefined HostValidationID = "machine-cidr-defined"

	// HostValidationIDHasDashCPUDashCoresDashForDashRole captures enum value "has-cpu-cores-for-role"
	HostValidationIDHasDashCPUDashCoresDashForDashRole HostValidationID = "has-cpu-cores-for-role"

	// HostValidationIDHasDashMemoryDashForDashRole captures enum value "has-memory-for-role"
	HostValidationIDHasDashMemoryDashForDashRole HostValidationID = "has-memory-for-role"

	// HostValidationIDHostnameDashUnique captures enum value "hostname-unique"
	HostValidationIDHostnameDashUnique HostValidationID = "hostname-unique"

	// HostValidationIDHostnameDashValid captures enum value "hostname-valid"
	HostValidationIDHostnameDashValid HostValidationID = "hostname-valid"

	// HostValidationIDBelongsDashToDashMachineDashCidr captures enum value "belongs-to-machine-cidr"
	HostValidationIDBelongsDashToDashMachineDashCidr HostValidationID = "belongs-to-machine-cidr"

	// HostValidationIDAPIDashVipDashConnected captures enum value "api-vip-connected"
	HostValidationIDAPIDashVipDashConnected HostValidationID = "api-vip-connected"

	// HostValidationIDBelongsDashToDashMajorityDashGroup captures enum value "belongs-to-majority-group"
	HostValidationIDBelongsDashToDashMajorityDashGroup HostValidationID = "belongs-to-majority-group"

	// HostValidationIDValidDashPlatformDashNetworkDashSettings captures enum value "valid-platform-network-settings"
	HostValidationIDValidDashPlatformDashNetworkDashSettings HostValidationID = "valid-platform-network-settings"

	// HostValidationIDNtpDashSynced captures enum value "ntp-synced"
	HostValidationIDNtpDashSynced HostValidationID = "ntp-synced"

	// HostValidationIDContainerDashImagesDashAvailable captures enum value "container-images-available"
	HostValidationIDContainerDashImagesDashAvailable HostValidationID = "container-images-available"

	// HostValidationIDLsoDashRequirementsDashSatisfied captures enum value "lso-requirements-satisfied"
	HostValidationIDLsoDashRequirementsDashSatisfied HostValidationID = "lso-requirements-satisfied"

	// HostValidationIDOcsDashRequirementsDashSatisfied captures enum value "ocs-requirements-satisfied"
	HostValidationIDOcsDashRequirementsDashSatisfied HostValidationID = "ocs-requirements-satisfied"

	// HostValidationIDSufficientDashInstallationDashDiskDashSpeed captures enum value "sufficient-installation-disk-speed"
	HostValidationIDSufficientDashInstallationDashDiskDashSpeed HostValidationID = "sufficient-installation-disk-speed"

	// HostValidationIDCnvDashRequirementsDashSatisfied captures enum value "cnv-requirements-satisfied"
	HostValidationIDCnvDashRequirementsDashSatisfied HostValidationID = "cnv-requirements-satisfied"

	// HostValidationIDSufficientDashNetworkDashLatencyDashRequirementDashForDashRole captures enum value "sufficient-network-latency-requirement-for-role"
	HostValidationIDSufficientDashNetworkDashLatencyDashRequirementDashForDashRole HostValidationID = "sufficient-network-latency-requirement-for-role"

	// HostValidationIDSufficientDashPacketDashLossDashRequirementDashForDashRole captures enum value "sufficient-packet-loss-requirement-for-role"
	HostValidationIDSufficientDashPacketDashLossDashRequirementDashForDashRole HostValidationID = "sufficient-packet-loss-requirement-for-role"

	// HostValidationIDHasDashDefaultDashRoute captures enum value "has-default-route"
	HostValidationIDHasDashDefaultDashRoute HostValidationID = "has-default-route"

	// HostValidationIDAPIDashDomainDashNameDashResolvedDashCorrectly captures enum value "api-domain-name-resolved-correctly"
	HostValidationIDAPIDashDomainDashNameDashResolvedDashCorrectly HostValidationID = "api-domain-name-resolved-correctly"

	// HostValidationIDAPIDashIntDashDomainDashNameDashResolvedDashCorrectly captures enum value "api-int-domain-name-resolved-correctly"
	HostValidationIDAPIDashIntDashDomainDashNameDashResolvedDashCorrectly HostValidationID = "api-int-domain-name-resolved-correctly"

	// HostValidationIDAppsDashDomainDashNameDashResolvedDashCorrectly captures enum value "apps-domain-name-resolved-correctly"
	HostValidationIDAppsDashDomainDashNameDashResolvedDashCorrectly HostValidationID = "apps-domain-name-resolved-correctly"

	// HostValidationIDCompatibleDashWithDashClusterDashPlatform captures enum value "compatible-with-cluster-platform"
	HostValidationIDCompatibleDashWithDashClusterDashPlatform HostValidationID = "compatible-with-cluster-platform"

	// HostValidationIDDNSDashWildcardDashNotDashConfigured captures enum value "dns-wildcard-not-configured"
	HostValidationIDDNSDashWildcardDashNotDashConfigured HostValidationID = "dns-wildcard-not-configured"

	// HostValidationIDDiskDashEncryptionDashRequirementsDashSatisfied captures enum value "disk-encryption-requirements-satisfied"
	HostValidationIDDiskDashEncryptionDashRequirementsDashSatisfied HostValidationID = "disk-encryption-requirements-satisfied"
)

// for schema
var hostValidationIdEnum []interface{}

func init() {
	var res []HostValidationID
	if err := json.Unmarshal([]byte(`["connected","has-inventory","has-min-cpu-cores","has-min-valid-disks","has-min-memory","machine-cidr-defined","has-cpu-cores-for-role","has-memory-for-role","hostname-unique","hostname-valid","belongs-to-machine-cidr","api-vip-connected","belongs-to-majority-group","valid-platform-network-settings","ntp-synced","container-images-available","lso-requirements-satisfied","ocs-requirements-satisfied","sufficient-installation-disk-speed","cnv-requirements-satisfied","sufficient-network-latency-requirement-for-role","sufficient-packet-loss-requirement-for-role","has-default-route","api-domain-name-resolved-correctly","api-int-domain-name-resolved-correctly","apps-domain-name-resolved-correctly","compatible-with-cluster-platform","dns-wildcard-not-configured","disk-encryption-requirements-satisfied"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostValidationIdEnum = append(hostValidationIdEnum, v)
	}
}

func (m HostValidationID) validateHostValidationIDEnum(path, location string, value HostValidationID) error {
	if err := validate.EnumCase(path, location, value, hostValidationIdEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this host validation id
func (m HostValidationID) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateHostValidationIDEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this host validation id based on context it is used
func (m HostValidationID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
