// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// StepType step type
//
// swagger:model step-type
type StepType string

func NewStepType(value StepType) *StepType {
	v := value
	return &v
}

const (

	// StepTypeConnectivityDashCheck captures enum value "connectivity-check"
	StepTypeConnectivityDashCheck StepType = "connectivity-check"

	// StepTypeExecute captures enum value "execute"
	StepTypeExecute StepType = "execute"

	// StepTypeInventory captures enum value "inventory"
	StepTypeInventory StepType = "inventory"

	// StepTypeInstall captures enum value "install"
	StepTypeInstall StepType = "install"

	// StepTypeFreeDashNetworkDashAddresses captures enum value "free-network-addresses"
	StepTypeFreeDashNetworkDashAddresses StepType = "free-network-addresses"

	// StepTypeResetDashInstallation captures enum value "reset-installation"
	StepTypeResetDashInstallation StepType = "reset-installation"

	// StepTypeDhcpDashLeaseDashAllocate captures enum value "dhcp-lease-allocate"
	StepTypeDhcpDashLeaseDashAllocate StepType = "dhcp-lease-allocate"

	// StepTypeAPIDashVipDashConnectivityDashCheck captures enum value "api-vip-connectivity-check"
	StepTypeAPIDashVipDashConnectivityDashCheck StepType = "api-vip-connectivity-check"

	// StepTypeNtpDashSynchronizer captures enum value "ntp-synchronizer"
	StepTypeNtpDashSynchronizer StepType = "ntp-synchronizer"

	// StepTypeInstallationDashDiskDashSpeedDashCheck captures enum value "installation-disk-speed-check"
	StepTypeInstallationDashDiskDashSpeedDashCheck StepType = "installation-disk-speed-check"

	// StepTypeContainerDashImageDashAvailability captures enum value "container-image-availability"
	StepTypeContainerDashImageDashAvailability StepType = "container-image-availability"

	// StepTypeDomainDashResolution captures enum value "domain-resolution"
	StepTypeDomainDashResolution StepType = "domain-resolution"
)

// for schema
var stepTypeEnum []interface{}

func init() {
	var res []StepType
	if err := json.Unmarshal([]byte(`["connectivity-check","execute","inventory","install","free-network-addresses","reset-installation","dhcp-lease-allocate","api-vip-connectivity-check","ntp-synchronizer","installation-disk-speed-check","container-image-availability","domain-resolution"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		stepTypeEnum = append(stepTypeEnum, v)
	}
}

func (m StepType) validateStepTypeEnum(path, location string, value StepType) error {
	if err := validate.EnumCase(path, location, value, stepTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this step type
func (m StepType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateStepTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this step type based on context it is used
func (m StepType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
